nodeSelector: {}
affinity: {}
tolerations: []
images:
  es:
    repository: quay.io/astronomer/ap-elasticsearch
    tag: 8.19.12
    pullPolicy: IfNotPresent
  init:
    repository: quay.io/astronomer/ap-base
    tag: 2026.03.24
    pullPolicy: IfNotPresent
  curator:
    repository: quay.io/astronomer/ap-curator
    tag: 8.0.21-10
    pullPolicy: IfNotPresent
  exporter:
    repository: quay.io/astronomer/ap-elasticsearch-exporter
    tag: 1.10.0
    pullPolicy: IfNotPresent
  nginx:
    repository: quay.io/astronomer/ap-nginx-es
    tag: 1.29.6
    pullPolicy: IfNotPresent
common:
  podAnnotations: {}
  serviceType: ClusterIP
  protocol: http
  serviceAccount:
    create: true
    annotations: {}
    name: null
    sccEnabled: true
  env:
    CLUSTER_NAME: astronomer
    HTTP_CORS_ENABLE: 'true'
    HTTP_CORS_ALLOW_ORIGIN: '*'
    NUMBER_OF_MASTERS: '2'
    MAX_LOCAL_STORAGE_NODES: '1'
    SHARD_ALLOCATION_AWARENESS: ''
    SHARD_ALLOCATION_AWARENESS_ATTR: ''
  persistence:
    enabled: true
    annotations: {}
    persistentVolumeClaimRetentionPolicy: null
  ports:
    http: 9200
    readiness: 9399
    transport: 9300
client:
  podAnnotations: {}
  replicas: 2
  maxUnavailable: 25%
  antiAffinity: soft
  initResources: {}
  heapMemory: 256m
  resources:
    requests:
      memory: 256Mi
  livenessProbe: {}
  readinessProbe: {}
  env:
    NODE_DATA: 'false'
    NODE_MASTER: 'false'
    NODE_INGEST: 'true'
    HTTP_ENABLE: 'true'
  roles:
  - ingest
  - ml
  - remote_cluster_client
data:
  podAnnotations: {}
  replicas: 2
  antiAffinity: soft
  initResources: {}
  heapMemory: 256m
  resources:
    requests:
      memory: 256Mi
  livenessProbe: {}
  readinessProbe: {}
  env:
    NODE_DATA: 'true'
    NODE_MASTER: 'false'
    NODE_INGEST: 'false'
    HTTP_ENABLE: 'false'
  roles:
  - data
  - data_cold
  - data_content
  - data_frozen
  - data_hot
  - data_warm
  - ml
  - remote_cluster_client
  - transform
  persistence:
    size: 50Gi
master:
  podAnnotations: {}
  replicas: 3
  antiAffinity: soft
  initResources: {}
  heapMemory: 256m
  resources:
    requests:
      memory: 256Mi
  readinessProbe: {}
  livenessProbe: {}
  env:
    NODE_DATA: 'false'
    NODE_MASTER: 'true'
    NODE_INGEST: 'false'
    HTTP_ENABLE: 'false'
  roles:
  - master
  - ml
  - remote_cluster_client
  persistence:
    size: 20Gi
curator:
  podAnnotations: {}
  enabled: true
  schedule: 0 1 * * *
  securityContext:
    runAsNonRoot: true
  resources: {}
  age:
    timestring: '%Y.%m.%d'
    unit: days
    unit_count: 10
  livenessProbe: {}
  readinessProbe: {}
exporter:
  podAnnotations: {}
  replicas: 1
  restartPolicy: Always
  podSecurityContext: {}
  securityContext:
    capabilities:
      drop:
      - ALL
  resources: {}
  livenessProbe: {}
  readinessProbe: {}
  service:
    type: ClusterIP
    httpPort: 9108
    annotations: {}
  es:
    timeout: 30s
  web:
    path: /metrics
nginx:
  replicas: 1
  podAnnotations: {}
  fullnameOverride: null
  ingressClass: null
  resources: {}
  securityContext:
    runAsNonRoot: true
  maxBodySize: 100M
  authCache:
    enabled: true
    levels: '1:2'
    keysZone: auth_cache:10m
    maxSize: 100m
    inactive: 5m
    validSuccess: 5m
    validFailure: 1m
sysctlInitContainer:
  enabled: true
  sysctlVmMaxMapCount: 262144
  livenessProbe: {}
  readinessProbe: {}
podSecurityContext:
  fsGroup: 1000
securityContext:
  capabilities:
    drop:
    - ALL
  runAsNonRoot: true
  runAsUser: 1000
ingress:
  annotation: {}
