image:
  repository: quay.io/astronomer/ap-pgbouncer-krb
  tag: 1.25.0-2
  pullPolicy: IfNotPresent
securityContext:
  runAsNonRoot: true
internalPort: 6543
servicePort: 6543
podDisruptionBudget:
  enabled: false
  config: {}
networkPolicies:
  enabled: true
serviceAccount:
  create: true
  annotations: {}
  name: null
env: []
podAnnotations: {}
resources:
  requests:
    memory: 256Mi
    cpu: 250m
  limits:
    memory: 256Mi
    cpu: 250m
readinessProbe: {}
livenessProbe: {}
extraVolumes: []
extraVolumeMounts: []
networkPolices:
  enabled: true
nodeSelector: {}
affinity: {}
tolerations: []
